### ISSUE TITLE
Need to fix the "max" column

### ISSUE THREAD

**Issue by EdsonMSouza** [traue/random_range_gen_php#3]
Need to fix the "max" column as it is breaking the line. 
![image](https://user-images.githubusercontent.com/8557164/134283950-09ef0982-fef4-4b73-b701-a216743ecc0b.png)

**Comment by traue** [comment]
HI, 
Fixed and updated in https://traue.com.br/random_range

Can you please double check? :)

Thanks a lot 🥇

**Comment by EdsonMSouza** [comment]
Hi, 
I did a test and it looks like everything is fine now.
